CREATE TABLE JH_EMPLOYEE
(
  EMP_NO VARCHAR2(20),
  EMP_ID VARCHAR2(30),
  EMP_PWD VARCHAR2(50),
  EMP_RRN VARCHAR2(50),
  EMP_NAME VARCHAR2(30),
  PHONE VARCHAR2(30),
  EMAIL VARCHAR2(50)
);
COMMENT ON COLUMN JH_EMPLOYEE.EMP_NO IS '번호';
COMMENT ON COLUMN JH_EMPLOYEE.EMP_ID IS '아이디';
COMMENT ON COLUMN JH_EMPLOYEE.EMP_PWD IS '비밀번호';
COMMENT ON COLUMN JH_EMPLOYEE.EMP_RRN IS '주민등록번호';
COMMENT ON COLUMN JH_EMPLOYEE.EMP_NAME IS '이름';
COMMENT ON COLUMN JH_EMPLOYEE.PHONE IS '전화번호';
COMMENT ON COLUMN JH_EMPLOYEE.EMAIL IS '이메일';

CREATE SEQUENCE EMP_NO
START WITH 1
INCREMENT BY 1
MAXVALUE 20
NOCYCLE
NOCACHE;

INSERT INTO JH_EMPLOYEE (EMP_NO, EMP_ID, EMP_PWD, EMP_RRN, EMP_NAME, PHONE, EMAIL)
VALUES (EMP_NO.NEXTVAL, 'USER1', 'PASSWORD1', '970412-1245342', '이진호', '010-8876-9797', 'dksdj898@naver.com');
INSERT INTO JH_EMPLOYEE (EMP_NO, EMP_ID, EMP_PWD, EMP_RRN, EMP_NAME, PHONE, EMAIL)
VALUES (EMP_NO.NEXTVAL, 'USER2', 'PASSWORD2', '990412-2245342', '이지혜', '010-5451-9797', 'wesd821@naver.com');
INSERT INTO JH_EMPLOYEE (EMP_NO, EMP_ID, EMP_PWD, EMP_RRN, EMP_NAME, PHONE, EMAIL)
VALUES (EMP_NO.NEXTVAL, 'USER3', 'PASSWORD3', '870412-1875442', '이지훈', '010-1245-2456', 'sdertt@naver.com');
INSERT INTO JH_EMPLOYEE (EMP_NO, EMP_ID, EMP_PWD, EMP_RRN, EMP_NAME, PHONE, EMAIL)
VALUES (EMP_NO.NEXTVAL, 'USER4', 'PASSWORD4', '940212-2454544', '이지헌', '010-5346-1237', 'gdgwe@naver.com');
INSERT INTO JH_EMPLOYEE (EMP_NO, EMP_ID, EMP_PWD, EMP_RRN, EMP_NAME, PHONE, EMAIL)
VALUES (EMP_NO.NEXTVAL, 'USER5', 'PASSWORD5', '911225-2232334', '이현', '010-2464-4523', 'sadgadg@naver.com');
INSERT INTO JH_EMPLOYEE (EMP_NO, EMP_ID, EMP_PWD, EMP_RRN, EMP_NAME, PHONE, EMAIL)
VALUES (EMP_NO.NEXTVAL, 'USER6', 'PASSWORD6', '920505-1975541', '이지헌', '010-4365-3252', 'adsgsdg@naver.com');
INSERT INTO JH_EMPLOYEE (EMP_NO, EMP_ID, EMP_PWD, EMP_RRN, EMP_NAME, PHONE, EMAIL)
VALUES (EMP_NO.NEXTVAL, 'USER7', 'PASSWORD7', '930111-2324891', '이지효', '010-4136-1235', 'hdfbdf@naver.com');

ALTER TABLE JH_EMPLOYEE
ADD CONSTRAINT UN_EMP_ID UNIQUE(EMP_ID);
ALTER TABLE JH_EMPLOYEE
MODIFY EMP_ID CONSTRAINT NN_EMP_ID NOT NULL;
ALTER TABLE JH_EMPLOYEE
MODIFY EMP_PWD CONSTRAINT NN_EMP_PWD NOT NULL;
ALTER TABLE JH_EMPLOYEE
ADD CONSTRAINT UN_EMP_RRN UNIQUE(EMP_RRN);
ALTER TABLE JH_EMPLOYEE
MODIFY EMP_RRN CONSTRAINT NN_EMP_RRN NOT NULL;
ALTER TABLE JH_EMPLOYEE
MODIFY EMP_NAME CONSTRAINT NN_EMP_NAME NOT NULL;
ALTER TABLE JH_EMPLOYEE
MODIFY PHONE CONSTRAINT NN_PHONE NOT NULL;
ALTER TABLE JH_EMPLOYEE
MODIFY EMAIL CONSTRAINT NN_EMAIL NOT NULL;
commit;
